### ISSUE TITLE
pip 21 doesn't support python 3.5

### ISSUE THREAD

**Issue by mihamerstan** [eokeeffe/D-FCN_Docker#1]
https://github.com/eokeeffe/D-FCN_Docker/blob/75ee7cf03f0ac0def563bd4457b3bbedb96fafc8/Dockerfile.dfcn#L53

This line causes errors in the following lines. It works if you modify to:
RUN python3.5 -m pip install --upgrade "pip < 21.0"

**Comment by eokeeffe** [comment]
Grand, line 53 has now been modified to the suggested string.
See repo at commit  a3f9e57cf72282703d59c327382d89c421f8d79d
